### ISSUE TITLE
Crash on fabric 1.19.2  when clicking create new world

### ISSUE THREAD

**Issue by Noogi420** [MehVahdJukaar/SnowySpirit#15]
Crash only happens with this mod.

---- Minecraft Crash Report ----
// You're mean.

Time: 2022-08-21 18:33:29
Description: mouseClicked event handler

java.lang.NullPointerException: mouseClicked event handler
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$getCodec$10(KeyDispatchCodec.java:123)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.codecs.KeyDispatchCodec.getCodec(KeyDispatchCodec.java:123)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$new$0(KeyDispatchCodec.java:46)
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:79)
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96)
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14)
	at net.minecraft.class_5506$class_5507.method_31159(class_5506.java:120)
	at net.minecraft.class_5455.method_31141(class_5455.java:280)
	at net.minecraft.class_5455.method_40314(class_5455.java:266)
	at net.minecraft.class_525.mda37dd9$lambda$wt_NewDefaultSettings$0$0(class_525.java:792)
	at net.minecraft.class_7237.method_42098(class_7237.java:24)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_528.method_43462(class_528.java:147)
	at net.minecraft.class_528.<init>(class_528.java:91)
	at net.minecraft.class_526.method_25426(class_526.java:65)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_310.method_1507(class_310.java:1035)
	at net.minecraft.class_442.method_19861(class_442.java:160)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:343)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$getCodec$10(KeyDispatchCodec.java:123)
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
	at com.mojang.serialization.codecs.KeyDispatchCodec.getCodec(KeyDispatchCodec.java:123)
	at com.mojang.serialization.codecs.KeyDispatchCodec.lambda$new$0(KeyDispatchCodec.java:46)
	at com.mojang.serialization.codecs.KeyDispatchCodec.encode(KeyDispatchCodec.java:79)
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:96)
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14)
	at net.minecraft.class_5506$class_5507.method_31159(class_5506.java:120)
	at net.minecraft.class_5455.method_31141(class_5455.java:280)
	at net.minecraft.class_5455.method_40314(class_5455.java:266)
	at net.minecraft.class_525.mda37dd9$lambda$wt_NewDefaultSettings$0$0(class_525.java:792)
	at net.minecraft.class_7237.method_42098(class_7237.java:24)
	at net.minecraft.class_525.method_31130(class_525.java:144)
	at net.minecraft.class_528.method_43462(class_528.java:147)
	at net.minecraft.class_528.<init>(class_528.java:91)
	at net.minecraft.class_526.method_25426(class_526.java:65)
	at net.minecraft.class_437.method_41843(class_437.java:389)
	at net.minecraft.class_437.method_25423(class_437.java:380)
	at net.minecraft.class_310.method_1507(class_310.java:1035)
	at net.minecraft.class_442.method_19861(class_442.java:160)
	at net.minecraft.class_4185.method_25306(class_4185.java:43)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:120)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_442.method_25402(class_442.java:343)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_442
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:489)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:103)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:222)
	at net.minecraft.class_310.method_1523(class_310.java:1208)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods, Supplementaries Generated Pack, EclecticTrove-noconfig-1.19-1.2.0.zip, EmbellishedStone-1.19-1.0.0.zip, Excalibur_Mod_Support_V1.18.1.1.zip, Excalibur_V1.18.1.zip, STONEBORN - 1.19 - V3.1.zip, STONEBORN - EXTENDED V1.3.zip, Snowyspirit Generated Pack
Stacktrace:
	at net.minecraft.class_6360.method_36565(class_6360.java:49)
	at net.minecraft.class_310.method_1587(class_310.java:2348)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1988459760 bytes (1896 MiB) / 3355443200 bytes (3200 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 SUPER
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x21c4
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1694
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21346.05
	Virtual memory used (MB): 16399.07
	Swap memory total (MB): 5026.40
	Swap memory used (MB): 291.94
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 4.0.0
		adorn: Adorn 3.6.1+1.19
		advancementplaques: Advancement Plaques 1.4.5
		adventurez: AdventureZ 1.4.14
		alaskanativecraft: Alaska Native Craft 1.4.7
		animatica: Animatica 0.5+1.19
		arcanus: Arcanus 1.30
		architects_palette: Architect's Palette Fabric 2.1.1
		architectury: Architectury 6.2.43
		archon: Archon 0.3.3
			cardinal-components-base: Cardinal Components API (base) 5.0.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.1
			omega-config: OmegaConfig 1.2.3-1.18.1
		attributefix: AttributeFix 17.0.1
		auudio: Auudio 1.0.3
		badpackets: Bad Packets 0.2.0
		balm-fabric: Balm 4.5.2+0
		bcc: BetterCompatibilityChecker 2.0.2-build.16+mc1.19.1
		bclib: BCLib 2.1.0
		betteradvancements: Better Advancements 0.2.2.142
		betterend: Better End 2.1.0
		bettermounthud: Better Mount HUD 1.1.4
		betternether: Better Nether 7.1.0
		betterthirdperson: Better Third Person 1.8.1
		bhmenu: BHMenu-Fabric 1.19-1.3
		biomemakeover: Biome Makeover 1.19.1-1.5.11
		blur: Blur (Fabric) 2.6.0
			satin: Satin 1.8.0
		bns: Brok N Sindri's Trinkets 1.1.2
		bookshelf: Bookshelf 16.0.3
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.4.2-1.19
			maelstrom_library: Maelstrom Library 1.3-1.19-pre1
			multipart_entities: MultipartEntities 1.2-1.19-pre1
		cardinal-components: Cardinal Components API 5.0.1
			cardinal-components-block: Cardinal Components API (blocks) 5.0.1
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.1
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.1
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.0.1
			cardinal-components-world: Cardinal Components API (worlds) 5.0.1
		carrier: Carrier 1.11.0
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.0.0-beta.3
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.0.0-beta.3
		charm: Charm 4.2.1
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		charmofundying: Charm of Undying 6.0.0+1.19.2
		chat_heads: Chat Heads 0.7.1
		cherishedworlds: Cherished Worlds 6.0.1+1.19.2
		citresewn: CIT Resewn 1.1.1+1.19
			citresewn-defaults: CIT Resewn: Defaults 1.1.1+1.19
		cloth-config: Cloth Config v8 8.0.75
			cloth-basic-math: cloth-basic-math 0.6.1
		collective-fabric: Collective (Fabric) 4.36
			fiber: fiber 0.23.0-2
		comforts: Comforts 6.0.0+1.19.2
			spectrelib: SpectreLib 0.8.1+1.19
		continuity: Continuity 2.0.1+1.19
		cosmetic-armor: Cosmetic Armor 1.4.0
		ctov: ChoiceTheorem's Overhauled Villages 3.0.1
		darkpaintings: DarkPaintings 13.0.1
		dataattributes: Data Attributes 1.2.5
		dawn: Dawn API 3.5.0
		debugify: Debugify 2.4.1
			com_github_llamalad7_mixinextras: mixinextras 0.0.12
		deepslatecutting: Deepslate Cutting 1.4.0
		dehydration: Dehydration 1.2.9
		dragonloot: DragonLoot 1.1.1
		drippyloadingscreen: Drippy Loading Screen 1.6.4
		duckling: Duckling 2.0.6
		dynamicsoundfilters: Dynamic Sound Filters 1.3.0+1.19
		echoingdepths: Echoing Descent 1.0.0-1.19.2
		elytraslot: Elytra Slot 6.0.0+1.19.2
		endrem: End Remastered 5.1.1
		fabric-api: Fabric API 0.59.0+1.19.2
			fabric-api-base: Fabric API Base 0.4.10+e62f51a390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.8+9ff28f4090
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.16+83a8659290
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.19+9ff28f4090
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.0+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.10+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.1.6+0c17ea9690
			fabric-commands-v0: Fabric Commands (v0) 0.2.27+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.33+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.2+83a8659290
			fabric-convention-tags-v1: Fabric Convention Tags 1.1.0+7cd20a1490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.4+bd0a0d4a90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.7+a680b9b490
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.29+a6d2f78590
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.17+9ff28f4090
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.27+9ff28f4090
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.27+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.20+1899036190
			fabric-item-api-v1: Fabric Item API (v1) 1.5.6+35a03c4390
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.27+6bee109e90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.19+9ff28f4090
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.17+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.1+83a8659290
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.2+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.5+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.2+176380a290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.13+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.16+9ff28f4090
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.3+5eb68ef290
			fabric-networking-v0: Fabric Networking (v0) 0.3.20+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.10+7675279690
			fabric-particles-v1: Fabric Particles (v1) 1.0.9+dc39553a90
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.23+23c4cfef90
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.9+84f79e9d90
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.11+5187d39f90
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.19+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.13+9ff28f4090
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.6+9ff28f4090
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.21+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.15+9ff28f4090
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.10+e62f51a390
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.6.0+6bee109e90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.25+f05effaf90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.12+9ff28f4090
			fabric-textures-v0: Fabric Textures (v0) 1.0.19+9ff28f4090
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.10+83a8659290
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.2.0+1e232e1390
		fabric-language-kotlin: Fabric Language Kotlin 1.8.2+kotlin.1.7.10
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.10
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.10
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.2
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.9
		fallingleaves: Falling Leaves 1.12.1+1.19
		fallingtree: FallingTree 3.9.2
		fancymenu: FancyMenu 2.12.1
		ferritecore: FerriteCore 4.2.1
		firstperson: FirstpersonModel 2.1.2
		forgeconfigapiport: Forge Config API Port 4.1.4
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		frame: Frame 0.26.0+1.19
			frame-api-base: Frame Base 0.2.1+906ebc04a9
			frame-blocks-v0: Frame Blocks (v0) 0.1.3+233e7428a9
			frame-config-v0: Frame Config (v0) 0.3.1+0fa45150a9
			frame-content-registries-v0: Frame Content Registries (v0) 0.4.0+2876b511a9
			frame-enchantments-v0: Frame Enchantments (v0) 0.1.0+4093105da9
				mm: Manningham Mills 2.3
			frame-game-rules-v0: Frame Game Rules (v0) 0.2.4+e7ce56a6a9
			frame-items-v0: Frame Items (v0) 0.1.3+906ebc04a9
			frame-loot-tables-v0: Frame Loot Tables (v0) 0.1.4+4f7341eca9
			frame-registries-v0: Frame Registries (v0) 0.1.1+0e0ec74ea9
			frame-rendering-v0: Frame Rendering (v0) 0.1.5+906ebc04a9
			frame-tabbed-item-groups-v0: Frame Tabbed Item Groups (v0) 0.2.4+0aca9b56a9
			frame-toymaker-v0: Frame Data Generation Helpers (v0) 0.6.1+b13741c3a9
			frame-woods-v0: Frame Woods (v0) 0.2.1+6a33fbada9
		friendlyfire: FriendlyFire 14.0.1
		geckolib3: Geckolib 3.1.15
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.5
		grounded_origins: Grounded Origins 1.2.1
			apugli: Apugli 1.7.2
		iceberg: Iceberg 1.0.46
		indium: Indium 1.0.7+mc1.19
		inventoryhud: Inventory HUD + 3.4.2
		iris: Iris 1.2.6
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.9.0beta2
			journeymap-api-fabric: JourneyMap API 1.19.1-1.9-fabric-SNAPSHOT
		kiwi: Kiwi Lib 8.0.1
		konkrete: Konkrete 1.5.0
		legendarytooltips: Legendary Tooltips 1.2.6
		lithium: Lithium 0.8.3
		lod: Distant Horizons 1.6.9a
		medievalmusic: Medieval Music Mod 1.19-1.8
		medievalorigins: Medieval Origins 1.19.x-4.1.2
		memoryleakfix: memory Leak Fix 1.19.1-0.7.0
		merchantmarkers: Merchant Markers 1.2.3
		midnightlib: MidnightLib 0.5.2
		minecraft: Minecraft 1.19.2
		modmenu: Mod Menu 4.0.6
		moonlight: Moonlight 1.19.2-2.0.17
		nochatreports: No Chat Reports 1.19.2-v1.10.1
		notenoughanimations: NotEnoughAnimations 1.6.1
		optigui: OptiGUI 1.1.1
			org_apache_commons_commons-text: commons-text 1.9
		origins: Origins 1.6.2
			apoli: Apoli 2.5.1
				additionalentityattributes: Additionalentityattributes 1.0.0+1.19
				calio: Calio 1.7.0
				playerabilitylib: Pal 1.6.0
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		origins-classes: Origins: Classes 1.4.0
		owo: oωo 0.7.3+1.19
		passablefoliage: Passable Foliage 1.19-fabric-5.0.1
		pehkui: Pehkui 3.4.0+1.14.4-1.19.2
			kanos_config: Kanos Config 0.3.1+1.14.4-1.19
		playerex: PlayerEx 3.3.5
			net_objecthunter_exp4j: exp4j 0.4.8
			opc: Offline Player Cache 0.6.2
			placeholder-api: Placeholder API 2.0.0-beta.7+1.19
		presencefootsteps: Presence Footsteps 1.6.1
			kirin: Kirin UI 1.11.0
		rare-ice: Rare Ice 0.5.0
		reeses-sodium-options: Reese's Sodium Options 1.4.6+mc1.19.2-build.55
		rocks: This Rocks! 1.6.1
		roughlyenoughitems: Roughly Enough Items 9.1.526
		roughlyenoughprofessions: Roughly Enough Professions 1.1.1
		sdrp: Simple Discord Rich Presence 2.0.1-build.17+mc1.19.1
		seasons: Fabric Seasons 1.4-BETA+1.19
		skinlayers: 3d Skin Layers 1.5.1-mc1.19.1
		smoothboot: Smooth Boot 1.19-1.7.1
		snowyspirit: Snowy Spirit 1.19.2-2.0.0
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		sodium-extra: Sodium Extra 0.4.6+mc1.19-build.47
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		stackrefill-fabric: Stack Refill (Fabric) 2.6
		starlight: Starlight 1.1.1+fabric.ae22326
		structory: Structory 1.0.1
		supplementaries: Supplementaries 1.19.2-2.0.14
		tooltiprareness: Tooltip Rareness 1.0.6
		transparent: Transparent 5.1.0
		trinkets: Trinkets 3.4.0
		twigs: Twigs 2.0.0-beta.8+1.19
		villagernames: Villager Names 4.0.6
		visuality: Visuality 0.5.1
		voidtotem: Void Totem 2.1.0
		voidz: VoidZ 1.0.8
		windchimes: Windchimes 1.2.1
		wolveswitharmor: Wolves With Armor 1.8.0-1.19
			maybe-data: Maybe data 1.3.2-1.19-rc2
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		woof: Woof 1.1.2-1.19
			advanced_runtime_resource_pack: Runtime Resource Pack 0.6.2
		wthit: wthit 5.10.0
	Loaded Shaderpack: (off)
	Launched Version: fabric-loader-0.14.9-1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.94, NVIDIA Corporation
	Window size: 2560x1440
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, Supplementaries Generated Pack, file/EclecticTrove-noconfig-1.19-1.2.0.zip, file/EmbellishedStone-1.19-1.0.0.zip, file/Excalibur_Mod_Support_V1.18.1.1.zip (incompatible), file/Excalibur_V1.18.1.zip (incompatible), file/STONEBORN - 1.19 - V3.1.zip, file/STONEBORN - EXTENDED V1.3.zip (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz

**Comment by MehVahdJukaar** [comment]
hm are you sure its caused by this? I cant replicate. Also note that the current version works on 1.19.1+

**Comment by Noogi420** [comment]
Well, I’m not 100% sure, but the crash only happens with this mod installed. Once removed my game works fine, I thought it might have been conflicting with Alaska native craft since that mod also adds dogsleds so I removed it, and kept Snowyspirit installed, but it still crashed. Idk what else it could be other than most likely is conflicting with another mod. And the game version shouldn’t be a problem because your mod is for 1.19.1+
