### ISSUE TITLE
World not able to access

### ISSUE THREAD

**Issue by MinecraftModderDailyDoseOfMods** [MehVahdJukaar/SnowySpirit#46]
When I join the world with this mod on the console said this then disconnect the world
[16:00:36] [Server thread/ERROR]: Couldn't place player in world
java.lang.IllegalArgumentException: Invalid message net.mehvahdjukaar.snowyspirit.wreath_stuff.network.ClientBoundSyncAllWreaths
	at TRANSFORMER/forge@43.2.4/net.minecraftforge.network.simple.IndexedMessageCodec.build(IndexedMessageCodec.java:132)
	at TRANSFORMER/forge@43.2.4/net.minecraftforge.network.simple.SimpleChannel.encodeMessage(SimpleChannel.java:68)
	at TRANSFORMER/forge@43.2.4/net.minecraftforge.network.simple.SimpleChannel.toBuffer(SimpleChannel.java:81)
	at TRANSFORMER/forge@43.2.4/net.minecraftforge.network.simple.SimpleChannel.toVanillaPacket(SimpleChannel.java:112)
	at TRANSFORMER/forge@43.2.4/net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107)
	at TRANSFORMER/moonlight@1.19.2-2.2.2/net.mehvahdjukaar.moonlight.api.platform.network.forge.ChannelHandlerImpl.sendToClientPlayer(ChannelHandlerImpl.java:87)
	at TRANSFORMER/snowyspirit@1.19.2-2.1.5/net.mehvahdjukaar.snowyspirit.wreath_stuff.ServerEvents.onPlayerLogin(ServerEvents.java:67)
	at TRANSFORMER/snowyspirit@1.19.2-2.1.5/net.mehvahdjukaar.snowyspirit.wreath_stuff.__ServerEvents_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.4/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:765)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:246)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:156)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:143)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_9933_(ServerLoginPacketListenerImpl.java:75)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.Connection.m_129483_(Connection.java:248)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:118)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by MehVahdJukaar** [comment]
Hmm damn. Do you check if supplementaries and moonlight are up to date?

**Comment by MinecraftModderDailyDoseOfMods** [comment]
Update fix the problem,thanks

**Comment by MehVahdJukaar** [comment]
Are you sure you have updated? Both server and client
